//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.OA.Data;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.IntPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.IntPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class InfoFile_
    extends SharedPreferencesHelper
{


    public InfoFile_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public InfoFile_.InfoFileEditor_ edit() {
        return new InfoFile_.InfoFileEditor_(getSharedPreferences());
    }

    public StringPrefField AdminID() {
        return stringField("AdminID", "");
    }

    public IntPrefField ArcStepID() {
        return intField("ArcStepID", 0);
    }

    public StringPrefField CurNode() {
        return stringField("CurNode", "");
    }

    public StringPrefField DeptID() {
        return stringField("DeptID", "");
    }

    public IntPrefField FlowID() {
        return intField("FlowID", 0);
    }

    public IntPrefField FlowStepID() {
        return intField("FlowStepID", 0);
    }

    public IntPrefField NoticeID() {
        return intField("NoticeID", 0);
    }

    public IntPrefField ROOMID() {
        return intField("ROOMID", 0);
    }

    public StringPrefField RoleID() {
        return stringField("RoleID", "");
    }

    public IntPrefField RoomLogID() {
        return intField("RoomLogID", 0);
    }

    public IntPrefField StepDataID() {
        return intField("StepDataID", 0);
    }

    public StringPrefField Title() {
        return stringField("Title", "");
    }

    public IntPrefField TypeOfLast() {
        return intField("TypeOfLast", 0);
    }

    public IntPrefField WFID() {
        return intField("WFID", 0);
    }

    public IntPrefField WFStepID() {
        return intField("WFStepID", 0);
    }

    public StringPrefField WorkID() {
        return stringField("WorkID", "");
    }

    public StringPrefField addressOfMeeting() {
        return stringField("addressOfMeeting", "");
    }

    public StringPrefField endTime() {
        return stringField("endTime", "");
    }

    public IntPrefField flowid() {
        return intField("flowid", 0);
    }

    public StringPrefField infoPassword() {
        return stringField("infoPassword", "");
    }

    public StringPrefField infoUserType() {
        return stringField("infoUserType", "");
    }

    public StringPrefField infoUsername() {
        return stringField("infoUsername", "");
    }

    public StringPrefField infoUsername2() {
        return stringField("infoUsername2", "");
    }

    public BooleanPrefField isAutoLogin() {
        return booleanField("isAutoLogin", false);
    }

    public StringPrefField nameOfMeeting() {
        return stringField("nameOfMeeting", "");
    }

    public StringPrefField rnrsOfMeeting() {
        return stringField("rnrsOfMeeting", "");
    }

    public StringPrefField statusOfNotice() {
        return stringField("statusOfNotice", "");
    }

    public StringPrefField statusOfSHENHE() {
        return stringField("statusOfSHENHE", "");
    }

    public IntPrefField typeOfHyxxBottomButton() {
        return intField("typeOfHyxxBottomButton", 0);
    }

    public StringPrefField typeOfMeeting() {
        return stringField("typeOfMeeting", "");
    }

    public StringPrefField urlCenterWs() {
        return stringField("urlCenterWs", "");
    }

    public final static class InfoFileEditor_
        extends EditorHelper<InfoFile_.InfoFileEditor_>
    {


        InfoFileEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> AdminID() {
            return stringField("AdminID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> ArcStepID() {
            return intField("ArcStepID");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> CurNode() {
            return stringField("CurNode");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> DeptID() {
            return stringField("DeptID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> FlowID() {
            return intField("FlowID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> FlowStepID() {
            return intField("FlowStepID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> NoticeID() {
            return intField("NoticeID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> ROOMID() {
            return intField("ROOMID");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> RoleID() {
            return stringField("RoleID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> RoomLogID() {
            return intField("RoomLogID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> StepDataID() {
            return intField("StepDataID");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> Title() {
            return stringField("Title");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> TypeOfLast() {
            return intField("TypeOfLast");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> WFID() {
            return intField("WFID");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> WFStepID() {
            return intField("WFStepID");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> WorkID() {
            return stringField("WorkID");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> addressOfMeeting() {
            return stringField("addressOfMeeting");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> endTime() {
            return stringField("endTime");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> flowid() {
            return intField("flowid");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoPassword() {
            return stringField("infoPassword");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUserType() {
            return stringField("infoUserType");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUsername() {
            return stringField("infoUsername");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUsername2() {
            return stringField("infoUsername2");
        }

        public BooleanPrefEditorField<InfoFile_.InfoFileEditor_> isAutoLogin() {
            return booleanField("isAutoLogin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> nameOfMeeting() {
            return stringField("nameOfMeeting");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> rnrsOfMeeting() {
            return stringField("rnrsOfMeeting");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> statusOfNotice() {
            return stringField("statusOfNotice");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> statusOfSHENHE() {
            return stringField("statusOfSHENHE");
        }

        public IntPrefEditorField<InfoFile_.InfoFileEditor_> typeOfHyxxBottomButton() {
            return intField("typeOfHyxxBottomButton");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> typeOfMeeting() {
            return stringField("typeOfMeeting");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> urlCenterWs() {
            return stringField("urlCenterWs");
        }

    }

}
